[package]
name = "charlatan"
version = "0.1.0"
authors = ["VentGrey <omarpurataf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scanrs = "0.2.1"
colored = "2.0.0"
